FROM ubuntu:20.04

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update && \
    apt-get -yq install \
      wget libncurses5 libwxgtk3.0-gtk3-0v5 libwxbase3.0-0v5 libsctp1 \
      build-essential emacs git && \
    rm -rf /var/lib/apt/lists/*

ENV ERLANG_VERSION=26.0.2 \
    ERLANG_EMACS_LIB="/usr/lib/erlang/lib/tools-3.6/emacs"

RUN . /etc/os-release && \
    export FILE="esl-erlang_${ERLANG_VERSION}-1~ubuntu~${VERSION_CODENAME}_amd64.deb" && \
    wget -q "https://binaries2.erlang-solutions.com/ubuntu/pool/contrib/e/esl-erlang/$FILE" && \
    dpkg -i $FILE && \
    rm $FILE

WORKDIR /edts

COPY . .

RUN make && \
    make test
